---
- name: Install required packages for Docker (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-docker  # Added for Docker Python module
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install required packages for Docker (RedHat)
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - curl
      - python3-docker  # Added for Docker Python module
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Docker GPG key (Debian/Ubuntu)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository (RedHat)
  ansible.builtin.dnf:
    name: https://download.docker.com/linux/centos/docker-ce.repo
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_os_family in ["Debian", "RedHat"]

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: ansible_architecture == "x86_64"
